<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP2nC6BV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP2nC6BV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP2nC6BV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP2nC6BV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP2nC6BV\App_KernelDevDebugContainer([
    'container.build_hash' => 'P2nC6BV',
    'container.build_id' => '8df6f072',
    'container.build_time' => 1679999283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP2nC6BV');
