<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH2M3pbt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH2M3pbt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH2M3pbt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH2M3pbt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH2M3pbt\App_KernelDevDebugContainer([
    'container.build_hash' => 'H2M3pbt',
    'container.build_id' => 'abbd8077',
    'container.build_time' => 1679977969,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH2M3pbt');
