<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE5UEN7s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE5UEN7s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE5UEN7s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE5UEN7s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE5UEN7s\App_KernelDevDebugContainer([
    'container.build_hash' => 'E5UEN7s',
    'container.build_id' => '2b6828d0',
    'container.build_time' => 1679845776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE5UEN7s');
