version: "3.8"

networks:
 densou_net:
  driver: bridge
  ipam:
   driver: default

services:

    POSTGRES:
      image: postgres:latest
      hostname: postgres
      environment:
      - POSTGRES_PASSWORD=mysecretpassword
      networks:
       densou_net:
        aliases:
        - postgres
      volumes:
      - postgres-data:/var/lib/postgresql/data
      stdin_open: true
      tty: true 

    MAIN:
      image: main:1001
      working_dir: /app
      hostname: main
      networks:
       densou_net:
        aliases:
        - main
      volumes:
      - .:/app
      ports:
      - "8000:80"
      depends_on:
      - POSTGRES
      command: ["/bin/bash","-c","/etc/main/main_start_script.sh;/bin/bash"]
      stdin_open: true
      tty: true

volumes:
 postgres-data: