<?php

namespace ContainerH2M3pbt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExchangeRateControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ExchangeRateController' shared autowired service.
     *
     * @return \App\Controller\ExchangeRateController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ExchangeRateController.php';

        return $container->services['App\\Controller\\ExchangeRateController'] = new \App\Controller\ExchangeRateController(($container->privates['http_client'] ?? $container->load('getHttpClientService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
